/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2d3449",
        "inverse-primary": "#0057cc",
        "background": "#0b1326",
        "surface-container": "#171f33",
        "on-error": "#690005",
        "on-tertiary-fixed": "#370e00",
        "outline": "#8c90a0",
        "tertiary-container": "#bb4300",
        "secondary-fixed-dim": "#a0caff",
        "primary": "#b0c6ff",
        "surface-tint": "#b0c6ff",
        "primary-fixed-dim": "#b0c6ff",
        "surface-container-low": "#131b2e",
        "glass-stroke": "rgba(255, 255, 255, 0.1)",
        "error": "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "inverse-on-surface": "#283044",
        "on-secondary-container": "#002b4e",
        "on-primary-container": "#e7ecff",
        "secondary-fixed": "#d2e4ff",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "accent-red": "#E73636",
        "surface-bright": "#31394d",
        "on-primary-fixed": "#001945",
        "on-primary-fixed-variant": "#00419c",
        "surface-dark": "#0F172A",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#7f2b00",
        "primary-fixed": "#d9e2ff",
        "on-tertiary": "#5a1c00",
        "surface-container-high": "#222a3d",
        "surface": "#0b1326",
        "tertiary-fixed-dim": "#ffb599",
        "on-secondary": "#003259",
        "surface-dim": "#0b1326",
        "surface-light": "#1E293B",
        "accent-gold": "#F9D70B",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdbce",
        "on-secondary-fixed": "#001c37",
        "secondary": "#a0caff",
        "secondary-container": "#3694ec",
        "primary-container": "#0063e5",
        "on-primary": "#002c6f",
        "surface-container-lowest": "#060e20",
        "on-surface": "#dae2fd",
        "glass-fill": "rgba(15, 23, 42, 0.7)",
        "on-secondary-fixed-variant": "#00497e",
        "outline-variant": "#424654",
        "on-surface-variant": "#c2c6d7",
        "tertiary": "#ffb599",
        "on-tertiary-container": "#ffe7df"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "48px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-md": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "headline-sm": ["DM Sans", "sans-serif"],
        "label-lg": ["DM Sans", "sans-serif"],
        "headline-lg": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "display-lg": ["DM Sans", "sans-serif"],
        "display-lg-mobile": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      },
      maxWidth: {
        "container-max": "1440px"
      }
    },
  },
  plugins: [],
}
 